//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSWTest.Storage.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public decimal Price { get; set; }
        public string Picture { get; set; }
        public Nullable<System.Guid> IdAuthor { get; set; }
        public Nullable<System.Guid> IdCategory { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
    }
}
